version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000" # Expose both API and frontend
    env_file:
      - .env
    volumes:
      - ./chroma_langchain_db:/app/chroma_langchain_db
